name             'build_server'
maintainer       'Raintank, Inc.'
maintainer_email 'jeremy@raintank.io'
license          'Apache 2.0'
description      'Installs/Configures build_server'
long_description 'Installs/Configures build_server'
version          '0.1.0'

depends 'golang'
depends 'python'
