name             'build_server'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures build_server'
long_description 'Installs/Configures build_server'
version          '0.1.0'

depends 'golang'
depends 'python'
